(() => {
  "use strict";
  const URL = "https://lakcmrzaqjrypztlkegx.supabase.co";
  const KEY = "sb_publishable_3KkoA-9hVthbUzatMeGjZA_el0N5LK9";
  const SESSION_KEY = "peyvand_classroom_session";
  const $ = selector => document.querySelector(selector);
  const state = { session:null, profile:null, groups:[], profiles:[], group:null, poll:null };
  const copy = {
    fa:{classroom:"صنف آنلاین",logout:"خروج",welcome:"به صنف آنلاین خوش آمدید",welcomeText:"آموزگاران و شاگردان از حساب شخصی خود وارد گروه درسی می‌شوند.",name:"نام کامل",email:"ایمیل",password:"رمز عبور",login:"ورود",signup:"ثبت‌نام",needAccount:"حساب ندارید؟ ثبت‌نام کنید",haveAccount:"حساب دارید؟ وارد شوید",myGroups:"گروه‌های من",noGroups:"هنوز به هیچ گروهی اضافه نشده‌اید.",manage:"مدیریت گروه‌ها و کاربران",chooseGroup:"یک گروه را انتخاب کنید",chooseGroupText:"گفتگو، اعضا و صنف آنلاین در اینجا نمایش داده می‌شود.",startClass:"شروع صنف صوتی/تصویری",liveClass:"صنف آنلاین",close:"بستن",members:"اعضای گروه",messagePlaceholder:"پیام بنویسید…",newGroup:"گروه جدید",groupName:"نام گروه",description:"توضیحات",teacher:"آموزگار",createGroup:"ایجاد گروه",users:"کاربران",usersHelp:"کاربر ابتدا ثبت‌نام می‌کند؛ سپس نقش و گروه او را تعیین کنید.",addMember:"افزودن عضو به گروه",group:"گروه",person:"شخص",add:"افزودن",student:"شاگرد",admin:"مدیر",sent:"ارسال شد",saved:"ذخیره شد",created:"گروه ایجاد شد",added:"عضو اضافه شد",confirm:"حساب ایجاد شد. اگر ایمیل تأیید خواسته شد، ایمیل خود را بررسی کنید.",error:"عملیات انجام نشد. دوباره کوشش کنید.",teacherRole:"آموزگار",studentRole:"شاگرد",adminRole:"مدیر"},
    ps:{classroom:"آنلاین ټولګی",logout:"وتل",welcome:"آنلاین ټولګي ته ښه راغلاست",welcomeText:"ښوونکي او زده کوونکي د خپل حساب له لارې درسي ډلې ته ننوځي.",name:"بشپړ نوم",email:"برېښنالیک",password:"پټنوم",login:"ننوتل",signup:"نوم لیکنه",needAccount:"حساب نه لرئ؟ نوم لیکنه وکړئ",haveAccount:"حساب لرئ؟ ننوځئ",myGroups:"زما ډلې",noGroups:"تاسو لا کومې ډلې ته نه یاست ورزیات شوي.",manage:"د ډلو او کاروونکو اداره",chooseGroup:"یوه ډله وټاکئ",chooseGroupText:"خبرې، غړي او آنلاین ټولګی دلته ښکاري.",startClass:"غږیز/ویډیويي ټولګی پیل کړئ",liveClass:"آنلاین ټولګی",close:"بندول",members:"د ډلې غړي",messagePlaceholder:"پیغام ولیکئ…",newGroup:"نوې ډله",groupName:"د ډلې نوم",description:"تشریح",teacher:"ښوونکی",createGroup:"ډله جوړول",users:"کاروونکي",usersHelp:"کاروونکی لومړی نوم لیکنه کوي؛ بیا یې رول او ډله وټاکئ.",addMember:"ډلې ته غړی زیاتول",group:"ډله",person:"شخص",add:"زیاتول",saved:"خوندي شو",created:"ډله جوړه شوه",added:"غړی زیات شو",confirm:"حساب جوړ شو. که تایید وغوښتل شي، خپل برېښنالیک وګورئ.",error:"عملیه ناکامه شوه. بیا هڅه وکړئ.",teacherRole:"ښوونکی",studentRole:"زده کوونکی",adminRole:"مدیر"},
    de:{classroom:"Lernplattform",logout:"Abmelden",welcome:"Willkommen im PEYWAND-Klassenraum",welcomeText:"Lehrkräfte und Schüler öffnen ihre eigene geschützte Lerngruppe.",name:"Vollständiger Name",email:"E-Mail",password:"Passwort",login:"Anmelden",signup:"Registrieren",needAccount:"Noch kein Konto? Registrieren",haveAccount:"Schon registriert? Anmelden",myGroups:"Meine Gruppen",noGroups:"Du wurdest noch keiner Gruppe zugeordnet.",manage:"Gruppen und Nutzer verwalten",chooseGroup:"Wähle eine Gruppe",chooseGroupText:"Chat, Mitglieder und Online-Unterricht erscheinen hier.",startClass:"Audio-/Video-Unterricht starten",liveClass:"Online-Unterricht",close:"Schließen",members:"Gruppenmitglieder",messagePlaceholder:"Nachricht schreiben…",newGroup:"Neue Gruppe",groupName:"Gruppenname",description:"Beschreibung",teacher:"Lehrkraft",createGroup:"Gruppe erstellen",users:"Nutzer",usersHelp:"Nutzer registrieren sich zuerst. Danach legst du Rolle und Gruppe fest.",addMember:"Mitglied einer Gruppe zuordnen",group:"Gruppe",person:"Person",add:"Hinzufügen",saved:"Gespeichert",created:"Gruppe wurde erstellt",added:"Mitglied wurde hinzugefügt",confirm:"Konto erstellt. Falls eine Bestätigung verlangt wird, bitte E-Mail prüfen.",error:"Das hat nicht funktioniert. Bitte erneut versuchen.",teacherRole:"Lehrkraft",studentRole:"Schüler/in",adminRole:"Administrator"},
    en:{classroom:"Learning platform",logout:"Sign out",welcome:"Welcome to the PEYWAND classroom",welcomeText:"Teachers and students access their own protected learning group.",name:"Full name",email:"Email",password:"Password",login:"Sign in",signup:"Create account",needAccount:"No account yet? Register",haveAccount:"Already registered? Sign in",myGroups:"My groups",noGroups:"You have not been assigned to a group yet.",manage:"Manage groups and users",chooseGroup:"Choose a group",chooseGroupText:"Chat, members and online classes appear here.",startClass:"Start audio/video class",liveClass:"Online class",close:"Close",members:"Group members",messagePlaceholder:"Write a message…",newGroup:"New group",groupName:"Group name",description:"Description",teacher:"Teacher",createGroup:"Create group",users:"Users",usersHelp:"Users register first. Then assign their role and group.",addMember:"Add member to group",group:"Group",person:"Person",add:"Add",saved:"Saved",created:"Group created",added:"Member added",confirm:"Account created. If confirmation is required, check your email.",error:"That did not work. Please try again.",teacherRole:"Teacher",studentRole:"Student",adminRole:"Administrator"}
  };
  Object.assign(copy.fa,{username:"نام کاربری",loginHelp:"نام کاربری و رمز عبور را از مسئول PEYWAND دریافت می‌کنید.",newUser:"دسترسی جدید",newPassword:"رمز عبور اولیه",passwordHelp:"حداقل ۶ حرف؛ برای مثال Ali123",role:"نقش",createUser:"ساختن دسترسی",accessType:"نوع دسترسی",groupOverview:"گروه‌ها و اعضا",userCreated:"دسترسی ساخته شد",teachers:"آموزگاران",students:"شاگردان",remove:"حذف",usersHelp:"همه دسترسی‌ها را خودتان با نام کاربری و رمز عبور ایجاد می‌کنید."});
  Object.assign(copy.ps,{username:"کارن نوم",loginHelp:"کارن نوم او پټنوم د PEYWAND له مسئول څخه ترلاسه کوئ.",newUser:"نوی لاسرسی",newPassword:"لومړنی پټنوم",passwordHelp:"لږ تر لږه ۶ توري؛ د بېلګې په توګه Ali123",role:"رول",createUser:"لاسرسی جوړول",accessType:"د لاسرسي ډول",groupOverview:"ډلې او غړي",userCreated:"لاسرسی جوړ شو",teachers:"ښوونکي",students:"زده کوونکي",remove:"لرې کول",usersHelp:"ټول لاسرسي تاسو پخپله د کارن نوم او پټنوم سره جوړوئ."});
  Object.assign(copy.de,{username:"Benutzername",loginHelp:"Benutzername und Passwort erhältst du von PEYWAND.",newUser:"Neuen Zugang erstellen",newPassword:"Startpasswort",passwordHelp:"Mindestens 6 Zeichen, zum Beispiel Ali123",role:"Rolle",createUser:"Zugang erstellen",accessType:"Zugangsart",groupOverview:"Gruppen und Mitglieder",userCreated:"Zugang wurde erstellt",teachers:"Lehrkräfte",students:"Schüler",remove:"Entfernen",usersHelp:"Alle Zugänge erstellst du selbst mit Benutzername und Startpasswort."});
  Object.assign(copy.en,{username:"Username",loginHelp:"You receive your username and password from PEYWAND.",newUser:"Create new access",newPassword:"Initial password",passwordHelp:"At least 6 characters, for example Ali123",role:"Role",createUser:"Create access",accessType:"Access type",groupOverview:"Groups and members",userCreated:"Access created",teachers:"Teachers",students:"Students",remove:"Remove",usersHelp:"You create every account yourself with a username and initial password."});
  let lang = localStorage.getItem("peyvand_classroom_lang") || "fa";
  function t(key){ return copy[lang]?.[key] || copy.de[key] || key; }
  function translate(){ document.documentElement.lang=lang; document.documentElement.dir=["fa","ps"].includes(lang)?"rtl":"ltr"; $("#language").value=lang; document.querySelectorAll("[data-i18n]").forEach(el=>{el.textContent=t(el.dataset.i18n)}); document.querySelectorAll("[data-i18n-placeholder]").forEach(el=>{el.placeholder=t(el.dataset.i18nPlaceholder)}); $("#auth-submit").textContent=t("login"); if(state.profile) $("#profile-role").textContent=t(state.profile.role+"Role"); }
  function status(el,message,error=false){ el.textContent=message||""; el.classList.toggle("error",error); }
  function saveSession(session){ state.session=session; session?localStorage.setItem(SESSION_KEY,JSON.stringify(session)):localStorage.removeItem(SESSION_KEY); }
  async function refreshSession(){ if(!state.session?.refresh_token)return false; const res=await fetch(URL+"/auth/v1/token?grant_type=refresh_token",{method:"POST",headers:{apikey:KEY,"Content-Type":"application/json"},body:JSON.stringify({refresh_token:state.session.refresh_token})}); if(!res.ok){saveSession(null);return false} saveSession(await res.json());return true; }
  async function api(path,options={},retry=true){ const headers={apikey:KEY,"Content-Type":"application/json",...(options.headers||{})}; if(state.session?.access_token)headers.Authorization="Bearer "+state.session.access_token; const res=await fetch(URL+path,{...options,headers}); if(res.status===401&&retry&&await refreshSession())return api(path,options,false); return res; }
  async function jsonApi(path,options={}){ const res=await api(path,options); if(!res.ok)throw new Error(await res.text()); const text=await res.text(); return text?JSON.parse(text):null; }
  function escapeHtml(value){ const d=document.createElement("div");d.textContent=value??"";return d.innerHTML; }
  async function authenticate(event){ event.preventDefault(); const message=$("#auth-message"); status(message,""); const username=$("#username").value.trim(),password=$("#password").value; try{ const res=await fetch(URL+"/functions/v1/classroom-login",{method:"POST",headers:{apikey:KEY,"Content-Type":"application/json"},body:JSON.stringify({username,password})}); const data=await res.json(); if(!res.ok||!data.access_token)throw new Error("invalid_login"); saveSession(data);await boot(); }catch(error){status(message,t("error"),true);} }
  async function boot(){ if(!state.session?.user?.id){showAuth();return} try{ const rows=await jsonApi("/rest/v1/classroom_profiles?user_id=eq."+encodeURIComponent(state.session.user.id)+"&select=*"); if(!rows?.[0])throw new Error("profile"); state.profile=rows[0]; $("#auth-view").classList.add("hidden"); $("#app-view").classList.remove("hidden"); $("#logout").classList.remove("hidden"); $("#profile-name").textContent=state.profile.full_name; $("#profile-avatar").textContent=state.profile.full_name.trim()[0]?.toUpperCase()||"P"; $("#admin-tab").classList.toggle("hidden",state.profile.role!=="admin"); translate(); await loadGroups(); }catch(error){saveSession(null);showAuth();status($("#auth-message"),t("error"),true);} }
  function showAuth(){ $("#auth-view").classList.remove("hidden");$("#app-view").classList.add("hidden");$("#logout").classList.add("hidden"); }
  async function loadGroups(){ try{ state.groups=await jsonApi("/rest/v1/classroom_groups?select=id,name,description,teacher_id,video_room,active&active=eq.true&order=created_at.desc"); const list=$("#group-list");list.innerHTML="";state.groups.forEach(g=>{const b=document.createElement("button");b.type="button";b.className="group-item"+(state.group?.id===g.id?" active":"");b.innerHTML="<b>"+escapeHtml(g.name)+"</b><small>"+escapeHtml(g.description||"")+"</small>";b.onclick=()=>openGroup(g);list.append(b)});$("#group-empty").classList.toggle("hidden",state.groups.length>0); }catch(error){status($("#chat-status"),t("error"),true);} }
  async function openGroup(group){ state.group=group;$("#app-view").classList.add("room-open");$("#room-view").classList.remove("blank");$("#room-placeholder").classList.add("hidden");$("#room-content").classList.remove("hidden");$("#room-name").textContent=group.name;$("#room-description").textContent=group.description||"";await Promise.all([loadMessages(),loadMembers()]);await loadGroups();clearInterval(state.poll);state.poll=setInterval(loadMessages,3500); }
  async function loadMessages(){ if(!state.group)return; try{ const rows=await jsonApi("/rest/v1/classroom_messages?group_id=eq."+state.group.id+"&select=id,body,created_at,sender_id,sender:classroom_profiles!classroom_messages_sender_id_fkey(full_name,role)&order=created_at.asc&limit=200"); const box=$("#messages"),atBottom=box.scrollHeight-box.scrollTop-box.clientHeight<90; box.innerHTML=rows.map(m=>'<article class="message '+(m.sender_id===state.session.user.id?'mine':'')+'"><div class="message-head"><b>'+escapeHtml(m.sender?.full_name||"PEYWAND")+'</b><time>'+new Date(m.created_at).toLocaleTimeString([], {hour:"2-digit",minute:"2-digit"})+'</time></div><p>'+escapeHtml(m.body)+'</p></article>').join("");if(atBottom)box.scrollTop=box.scrollHeight;}catch(error){} }
  async function sendMessage(event){event.preventDefault();const body=$("#message-body").value.trim();if(!body||!state.group)return;try{await jsonApi("/rest/v1/classroom_messages",{method:"POST",headers:{Prefer:"return=representation"},body:JSON.stringify({group_id:state.group.id,sender_id:state.session.user.id,body})});$("#message-body").value="";await loadMessages();}catch(error){status($("#chat-status"),t("error"),true);} }
  async function loadMembers(){if(!state.group)return;try{const [students,teachers]=await Promise.all([jsonApi("/rest/v1/classroom_group_members?group_id=eq."+state.group.id+"&select=user_id,profile:classroom_profiles!classroom_group_members_user_id_fkey(full_name,role)&order=joined_at.asc"),jsonApi("/rest/v1/classroom_group_teachers?group_id=eq."+state.group.id+"&select=user_id,profile:classroom_profiles!classroom_group_teachers_user_id_fkey(full_name,role)&order=joined_at.asc")]);const members=[...(teachers||[]),...(students||[])];$("#member-list").innerHTML=members.map(m=>'<div class="member"><b>'+escapeHtml(m.profile?.full_name||"")+'</b><small>'+escapeHtml(t((m.profile?.role||"student")+"Role"))+'</small></div>').join("");}catch(error){} }
  function openVideo(){if(!state.group)return;$("#video-frame").src="https://meet.jit.si/PEYWAND-"+encodeURIComponent(state.group.video_room)+"#config.prejoinConfig.enabled=true&config.disableDeepLinking=true";$("#video-panel").classList.remove("hidden");}
  function closeVideo(){$("#video-frame").src="about:blank";$("#video-panel").classList.add("hidden");}
  async function openAdmin(){$("#app-view").classList.add("admin-open");$("#admin-view").classList.remove("hidden");try{state.profiles=await jsonApi("/rest/v1/classroom_profiles?select=*&order=created_at.asc");await loadGroups();await renderAdmin();}catch(error){}}
  function assignmentUsers(){const role=$("#assignment-role").value;const people=state.profiles.filter(p=>p.active&&p.role===role);$("#member-user").innerHTML=people.map(p=>'<option value="'+p.user_id+'">'+escapeHtml(p.full_name)+' · '+escapeHtml(p.username||"")+'</option>').join("");}
  async function renderAdmin(){$("#member-group").innerHTML=state.groups.map(g=>'<option value="'+g.id+'">'+escapeHtml(g.name)+'</option>').join("");assignmentUsers();$("#user-list").innerHTML="";state.profiles.forEach(p=>{const row=document.createElement("div");row.className="user-row";row.innerHTML='<div><b>'+escapeHtml(p.full_name)+'</b><small>@'+escapeHtml(p.username||"—")+'</small></div><select><option value="student">'+t("studentRole")+'</option><option value="teacher">'+t("teacherRole")+'</option><option value="admin">'+t("adminRole")+'</option></select>';const select=row.querySelector("select");select.value=p.role;select.disabled=p.user_id===state.session.user.id;select.onchange=async()=>{try{await jsonApi("/rest/v1/classroom_profiles?user_id=eq."+p.user_id,{method:"PATCH",headers:{Prefer:"return=minimal"},body:JSON.stringify({role:select.value})});p.role=select.value;await renderAdmin();}catch(error){select.value=p.role;}};$("#user-list").append(row)});await renderGroupOverview();}
  async function renderGroupOverview(){const [students,teachers]=await Promise.all([jsonApi("/rest/v1/classroom_group_members?select=group_id,user_id,profile:classroom_profiles!classroom_group_members_user_id_fkey(full_name)&order=joined_at.asc"),jsonApi("/rest/v1/classroom_group_teachers?select=group_id,user_id,profile:classroom_profiles!classroom_group_teachers_user_id_fkey(full_name)&order=joined_at.asc")]);$("#group-admin-list").innerHTML=state.groups.map(g=>{const chips=(rows,type)=>rows.filter(x=>x.group_id===g.id).map(x=>'<span class="assignment-chip"><b>'+escapeHtml(x.profile?.full_name||"")+'</b><button type="button" data-remove="'+type+'" data-group="'+g.id+'" data-user="'+x.user_id+'" aria-label="'+t("remove")+'">×</button></span>').join("")||'<small>—</small>';return '<article class="group-admin-row"><h4>'+escapeHtml(g.name)+'</h4><div class="assignment-section"><small>'+t("teachers")+'</small><div class="assignment-list">'+chips(teachers,"teacher")+'</div></div><div class="assignment-section"><small>'+t("students")+'</small><div class="assignment-list">'+chips(students,"student")+'</div></div></article>'}).join("");$("#group-admin-list").querySelectorAll("[data-remove]").forEach(button=>button.onclick=()=>removeAssignment(button));}
  async function removeAssignment(button){const table=button.dataset.remove==="teacher"?"classroom_group_teachers":"classroom_group_members";try{await jsonApi("/rest/v1/"+table+"?group_id=eq."+button.dataset.group+"&user_id=eq."+button.dataset.user,{method:"DELETE",headers:{Prefer:"return=minimal"}});await renderGroupOverview();}catch(error){}}
  async function createUser(event){event.preventDefault();const message=$("#user-form-status");status(message,"");try{const res=await api("/functions/v1/classroom-create-user",{method:"POST",body:JSON.stringify({username:$("#new-username").value.trim().toLowerCase(),full_name:$("#new-full-name").value.trim(),password:$("#new-password").value,role:$("#new-role").value})});const data=await res.json();if(!res.ok||!data.ok)throw new Error(data.error||"create_failed");event.target.reset();status(message,t("userCreated"));state.profiles=await jsonApi("/rest/v1/classroom_profiles?select=*&order=created_at.asc");await renderAdmin();}catch(error){status(message,error.message==="username_taken"?"Benutzername ist bereits vergeben.":t("error"),true);}}
  async function createGroup(event){event.preventDefault();try{await jsonApi("/rest/v1/classroom_groups",{method:"POST",headers:{Prefer:"return=representation"},body:JSON.stringify({name:$("#group-name").value.trim(),description:$("#group-description").value.trim(),created_by:state.session.user.id})});event.target.reset();status($("#group-form-status"),t("created"));await loadGroups();await renderAdmin();}catch(error){status($("#group-form-status"),t("error"),true);}}
  async function addMember(event){event.preventDefault();const role=$("#assignment-role").value;const table=role==="teacher"?"classroom_group_teachers":"classroom_group_members";try{await jsonApi("/rest/v1/"+table,{method:"POST",headers:{Prefer:"resolution=ignore-duplicates,return=minimal"},body:JSON.stringify({group_id:$("#member-group").value,user_id:$("#member-user").value})});status($("#member-form-status"),t("added"));await renderGroupOverview();}catch(error){status($("#member-form-status"),t("error"),true);}}
  $("#language").onchange=e=>{lang=e.target.value;localStorage.setItem("peyvand_classroom_lang",lang);translate();if(state.profile?.role==="admin")renderAdmin()};$("#auth-form").onsubmit=authenticate;$("#logout").onclick=()=>{saveSession(null);location.reload()};$("#refresh-groups").onclick=loadGroups;$("#message-form").onsubmit=sendMessage;$("#mobile-back").onclick=()=>{$("#app-view").classList.remove("room-open");clearInterval(state.poll)};$("#video-open").onclick=openVideo;$("#video-close").onclick=closeVideo;$("#admin-tab").onclick=openAdmin;$("#admin-back").onclick=()=>{$("#app-view").classList.remove("admin-open");$("#admin-view").classList.add("hidden")};$("#user-form").onsubmit=createUser;$("#group-form").onsubmit=createGroup;$("#member-form").onsubmit=addMember;$("#assignment-role").onchange=assignmentUsers;
  try{state.session=JSON.parse(localStorage.getItem(SESSION_KEY)||"null")}catch{} translate();boot();
})();
